var res = {
    //new
    bkgnd_png : "res/new/bkgnd.png",
    bkgndhelp_png : "res/new/bkgndhelp.png",
    menu_png  : "res/new/menu.png",
    menu_plist : "res/new/menu.plist",
    divers_png  : "res/new/divers.png",
    divers_plist : "res/new/divers.plist",
    nicolas_png  : "res/new/nicolas.png",
    nicolas_plist : "res/new/nicolas.plist",
    joanna_png  : "res/new/joanna.png",
    joanna_plist : "res/new/joanna.plist",
    monsters_png  : "res/new/monsters.png",
    monsters_plist : "res/new/monsters.plist",
    stone_png  : "res/new/tiles/stone/0.png",
    wood_png  : "res/new/tiles/wood/0.png",
    woodburn0_png  : "res/new/tiles/woodburn/0.png",
    woodburn1_png  : "res/new/tiles/woodburn/1.png",
    grass_png  : "res/new/tiles/grass/0.png",
    grassburn0_png  : "res/new/tiles/grassburn/0.png",
    grassburn1_png  : "res/new/tiles/grassburn/1.png",
    water_png  : "res/new/tiles/water/0.png",
    ice_png  : "res/new/tiles/ice/0.png",
    lava_png  : "res/new/tiles/lava/0.png",
    encophys_json : "res/encophys.json",
    heart_png : "res/new/heart.png",
    mana_png : "res/new/mana.png",
    level_png : "res/new/level.png",
    swordshoot_png : "res/new/swordshoot.png",
    title_png : "res/new/title.png",
    jshield_png : "res/new/jshield.png",
    nshield_png : "res/new/nshield.png",
    damage_png : "res/new/damage.png"
};

var g_resources = [
    //new
    res.encophys_json,
    res.bkgnd_png,
    res.bkgndhelp_png,
    res.menu_png,
    res.menu_plist,
    res.divers_png,
    res.divers_plist,
    res.nicolas_png,
    res.nicolas_plist,
    res.joanna_png,
    res.joanna_plist,
    res.monsters_png,
    res.monsters_plist,
    res.stone_png,
    res.wood_png,
    res.woodburn0_png,
    res.woodburn1_png,
    res.grass_png,
    res.grassburn0_png,
    res.grassburn1_png,
    res.water_png,
    res.ice_png,
    res.lava_png,
    res.heart_png,
    res.mana_png,
    res.level_png,
    res.swordshoot_png,
    res.title_png,
    res.jshield_png,
    res.nshield_png,
    res.damage_png
];
